version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:17.9.1

jobs:
  test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Install JUnit reporter
          command: npm install jest-junit
      - save_cache:
          key: v1-deps-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: Run tests
          command: npm test -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
  publish:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Inject NPM registry credential
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish the package
          command: npm publish

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: main
